### ISSUE TITLE
If/else statements for query

### ISSUE THREAD

**Issue by oliverbrooks** [orangemug/sql-stamp#13]
For queries with conditional filters (like many search queries).

Rather than SQL hacks like:

```SQL
SELECT
  *
FROM
  "pizza"
WHERE
  "pizza"."flavour" = {= flavour}
  AND
  (
    {? heat} IS NULL OR
    "pizza"."heat" = {= heat}
  )
```

I think it would be cleaner and easier to understand to do

```SQL
SELECT
  *
FROM
  "pizza"
WHERE
  "pizza"."flavour" = {= flavour}
  {#if heat}
  AND
  (
    "pizza"."heat" = {= heat}
  )
  {#/if}
```

This becomes especially apparent with complex queries. I know an objective was minimal but think this would make a big difference.

**Comment by pasupulaphani** [comment]
+1

**Comment by orangemug** [comment]
@oliverbrooks the original aims of sql-stamp was that the SQL template should be readable as SQL over something like handlebars which adds a lot of noise. I believe `if`s promote SQL templates which become hard to reason about and that ternary switches make the code easier to reason about.

Note that the SQL that's output from sql-stamp can be pasted into any REPL and all the structure is there to alter the query in place. Which I think is a big win for debugging complex queries, where as your suggestion you'd need to copy/paste other chunks in from the original file. This also the reason why the library outputs comments in the output (see https://github.com/orangemug/sql-stamp/blob/master/test/operators/feature/out.falsey.sql)

Currently I believe it should read

```
select
  *
from
  pizza
where
  pizza.flavour = "{= flavour}"
  AND (
    {?heatDisabled} OR pizza.heat = "{=heat}"
  )
```

The `{#if foo}{/if}` syntax suggestion above would allow large conditional switches, which I want to avoid.

If you however do need a more complex template engine <http://handlebarsjs.com/> should have you covered. Just add in a helper to escape SQL so it'll read something like

    select
      *
    from
      user
    where
      user.username = {{sqlEscape username}}

**Comment by orangemug** [comment]
Oh also note its not a "SQL hack" its just SQL

    {?searchDisabled} OR foo = "bar"

Is the same as

    false OR foo = "bar"

**Comment by oliverbrooks** [comment]
I kind of agree from a purity point of view, sql-stamp could aim to do only very basic string interpolation.

The question here is if the usefulness of such a feature would outweigh the minimalism. 

Worth noting that sql-stamp has already decided to do more than just string interpolation with the partial loading.

I feel we should discuss on two levels:

1. Decide if this is a useful feature enough to warrant a solution
2. If so, decide what is the output format such that it maintains SQL compatibility

### 1. Decision

Personally I think that the utility justifies the means. 

It makes both sql-stamp templates and the calling JS easier to read as it removes the `featureDisabled` variables which are not obvious in JS or template what they are for. 

The sql-stamp template is easier to read as it could make clearer which parts of the query are being run under certain conditions.

Avoiding the `{?disabledVar} OR thing` pattern would be a win. Negative logic is confusing at the best of times and when combined with multiple SQL statements makes it a real mind bender to understand.

sql-stamp templates must be compiled before they can be put into a sql engine anyway. 

One example of a real mind bender is conditional joins, for example `inner join categories` if there is a filter, otherwise skip. Can be done currently with a hack but will take 10m to understand what is going on when you look at it.

Downsides I see are:

* further away from pure string interpolation (although already have partials)
* as yet unexplored security and performance implications

### 2: What would the template and output SQL look like?

Could go down a few lines of thought. Given the simple example of:

```sql
SELECT
  *
FROM
  "pizza"
WHERE
  "pizza"."flavour" = {= flavour}
  AND "pizza"."heat" = {= heat}
```

If we want the `heat` var to be optional:

```js
sqlStamp("/path/to/sql.sql", {
  flavour: "fish"
});
```

We could write the template as such: 

```sql
SELECT
  *
FROM
  "pizza"
WHERE
  "pizza"."flavour" = {= flavour}
  {#if heat}
  AND "pizza"."heat" = {= heat}
  {#end heat}
```

Alternatives could be to extend the require syntax `{> ../partial.sql if(heat)}` so the partial is only loaded if the var is present although I think the former is cleaner.

Regarding output, different approaches could be:

1. Compile just the bits which are relevant
2. Compile with the unused bits commented out `/* AND "pizza"."heat" = 'undefined' */`
3. Compile into pure SQL logic statements `AND false OR "pizza"."heat" = ?`

I think my preference would be to compile with unused bits commented out, such as: 

```sql
SELECT
  *
FROM
  "pizza"
WHERE
  "pizza"."flavour" = {= flavour}
  /* 
  AND  "pizza"."heat" = 'undefined'
  */ 
```


Thoughts about implementation are a different matter entirely :)

**Comment by orangemug** [comment]
I'm still un-convinced there is a use case for this, take this javascript snippet is this difficult to understand?

   (featureDisabled || action());

**Comment by orangemug** [comment]
> Worth noting that sql-stamp has already decided to do more than just string interpolation with the partial loading.

In our case the require is just string interpolation, regardless of whats is doing behind the scenes.

    "a"+require("./b")+"c"

Is the same as this in my books as

   "a"+"b"+"c"

**Comment by orangemug** [comment]
> One example of a real mind bender is conditional joins, for example inner join categories if there is a filter, otherwise skip. Can be done currently with a hack but will take 10m to understand what is going on when you look at it.

Need context for this one

**Comment by orangemug** [comment]
**NOTE:** I've not tested this SQL so proceed with caution

It looks like you can use `CASE` statements in the `WHERE` also so

    SELECT
      *
    FROM
       pizza
    WHERE
      pizza.tasty = true
      AND CASE
        WHEN {?heatEnabled} THEN (
          "pizza"."heat" = {=heat}
        )
        ELSE true
      END

**Comment by orangemug** [comment]
Issue #23 and this ticket conflict. I think #23 is a must have for the future of sql-stamp so I'm closing this ticket.

Please feel free to comment if you have other thoughts

**Comment by orangemug** [comment]
I just tried a SQL version of the switch statements which I'll document fully in ticket #18 

In sqlite we can do

```sql
select
  *                            
from
  users
WHERE
  CASE
    WHEN ? THEN (users.status = 'active')
    ELSE 1
  END
  AND CASE
    WHEN ? THEN (users.role = 'admin')
    ELSE 1
  END
```

Where the arg would be

 * `[1,1]` to enable both filters
 * `[1,0]` to enable status filter
 * `[0,1]` to enable role filter

**NOTE:** sqlite does not support `true`/`false`

So in sql-stamp it would be

```sql
select
  *                            
from
  users
WHERE
  CASE
    WHEN {?enabledActiveFilter} THEN (users.status = 'active')
    ELSE 1
  END
  AND CASE                     
    WHEN {?enabledRoleFilter} THEN (users.role = 'admin')
    ELSE 1                     
  END
```

Note this also allows you to prepare the query ahead of time (see issue #23)
