### ISSUE TITLE
Error parsing Postgres array literals

### ISSUE THREAD

**Issue by oliverbrooks** [orangemug/sql-stamp#15]
Given a statement containing:

```sql
"account"."id" = ANY('{ {=ids} }'::int[])
```

The expected parsed SQL is:

```sql
"account"."id" = ANY('{?}'::int[])
```

Where `?` will be substituted with a list of items.

The actual output is:

```sql
"account"."id" = ANY('{?'::int[])
```

The trailing `}` is being removed.

Looks like the existing regex of `/(?:([^}{\n]+)|(\{(.)([^}]*)\})|([\n]))/gm` greedy matches the trailing `}`.

The value being passed in is a JS array of ids. I believe knex turns this into the required comma separated string of ids.

**Comment by orangemug** [comment]
Published in [v0.8.0](https://github.com/orangemug/sql-stamp/tree/v0.8.0)
