### ISSUE TITLE
Change from true/false to 1/0 in switch operator

### ISSUE THREAD

**Issue by orangemug** [orangemug/sql-stamp#24]
Change from `true`/`false` to `1`/`0` to support sqlite (and probably others) that don't support `true`/`false`

Lines to change <https://github.com/orangemug/sql-stamp/blob/675da538200523e9830271c7b801b37f0c9bedae/lib/operators/switch.js#L9-L11>

See <https://www.sqlite.org/datatype3.html#section_2_1>

**Comment by orangemug** [comment]
Requires research to check support for this in various db's

 * PostgreSQL
 * MySQL
 * Sqlite

We'll raise a separate ticket to test against databases.

**Comment by orangemug** [comment]
From docs

 - [**ok**] PostgreSQL: <https://www.postgresql.org/docs/9.1/static/datatype-boolean.html>
 - [**ok**] MySQL: <https://dev.mysql.com/doc/refman/5.7/en/boolean-literals.html>
 - [**ok**] SQLite: <https://www.sqlite.org/datatype3.html#section_2_1>

**Comment by oliverbrooks** [comment]
@orangemug might be worth considering how far sql-stamp goes on issues like this. 

Most people use just one kind of db and they could put the appropriate value in. 

An example of wanting multiple DB compatibility might be OSS but in that case they might be better off using sql-stamp in conjunction with something like knex which is tried and tested for db normalisation. 

Not got particularly strong opinions on this, just if this intends to remain lightweight this type of edge case stuff might be a path to rapid complexity growth.

**Comment by orangemug** [comment]
In this case I think its correct `1`/`0` is supported everywhere, I need to dig up the underlying spec for all of this but I'm thinking if its supported in MySQL, PostgreSQL and SQLite then I'm happy.

I think I want a really simple API that just works most places
