### ISSUE TITLE
In postgresql {} is the literal for an array

### ISSUE THREAD

**Issue by oliverbrooks** [orangemug/sql-stamp#8]
sql-stamp interprets the contents of curley braces `{}`. This means there is currently no way to create an array literal.

There is a possible work around by using a select statement but that is somewhat cumbersome. 

Would perhaps suggest moving the interpreted characters to handlebars style double curly braces `{{}}`.

**Comment by orangemug** [comment]
Is there any other character we could use? I like the single braces because it keeps the SQL clean and readable. Any thoughts?

**Comment by orangemug** [comment]
Also it doesn't look like `{{` will work either 

    {{"meeting", "lunch"}, {"training", "presentation"}}

http://www.postgresql.org/docs/9.1/static/arrays.html

**Comment by orangemug** [comment]
@oliverbrooks actually we'll just change `{this}` to `{=this}`. All the other operators include a prefix anyway so this should just work. I've got a v2 branch on the go and will add this to that branch. Operators will be

 * `{=key, optionalDefault}`  - Turns args into `?` with an optional default
 * `{!key, optionalDefault}` - Passed raw into the SQL
 * `{>path, optionalDataKey}` - Require file from the templates 
 * `{?key, replaceTruthy, replaceFalsey}` - Ternary switch, the defaults are replaceTruthy/replaceFalsey === true/false

**Comment by orangemug** [comment]
@oliverbrooks can you take a look make sure this makes sense to you, I'll do this to v0.7.0 if you're happy

**Comment by orangemug** [comment]
Released in `v0.7.0`
